spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/FitForge_user_db
    username: postgres
    password: Aaryaman0807
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
